In [1]:
import torch

In [ ]:
# adding tensors to constants or other tensors 
tensor1 = torch.rand(1,2,2) 
print(f"tensor1 is: {tensor1}")
print(f"Addition of tensor1 and 3 is: {tensor1 + 3}") 
tensor2 = torch.rand(1,2,2)
print(f"tensor2 is {tensor2}")
print(f"Addition of tensor1 and tensor2 is: {tensor1 + tensor2}")
print(torch.add(tensor1,tensor2))

tensor1 is: tensor([[[0.1709, 0.8005],
         [0.9328, 0.1264]]])
Addition of tensor1 and 3 is: tensor([[[3.5987, 3.5065],
         [3.0447, 3.4821]]])
tensor2 is tensor([[[0.7718, 0.1707],
         [0.9349, 0.4511]]])
Addition of tensor1 and tensor2 is: tensor([[[1.3705, 0.6772],
         [0.9796, 0.9332]]])
tensor([[[1.3705, 0.6772],
         [0.9796, 0.9332]]])


In [10]:
# subtracting constants from tensors or other tensors
tensor1 = torch.rand(2,3,4) 
print(f"tensor1 is: {tensor1}")
print(f"Subtraction between of tensor1 and 3 is: {tensor1 - 3}") 
tensor2 = torch.rand(2,3,4)
print(f"tensor2 is {tensor2}")
print(f"Subtraction between tensor1 and tensor2 is: {tensor1 - tensor2}")
print(torch.subtract(tensor1,tensor2))

tensor1 is: tensor([[[0.2937, 0.1317, 0.6548, 0.7472],
         [0.9010, 0.1713, 0.9218, 0.6804],
         [0.8042, 0.3988, 0.9878, 0.9226]],

        [[0.0492, 0.5925, 0.0320, 0.3182],
         [0.5489, 0.3986, 0.7618, 0.4883],
         [0.8719, 0.2523, 0.7609, 0.8824]]])
Subtraction between of tensor1 and 3 is: tensor([[[-2.7063, -2.8683, -2.3452, -2.2528],
         [-2.0990, -2.8287, -2.0782, -2.3196],
         [-2.1958, -2.6012, -2.0122, -2.0774]],

        [[-2.9508, -2.4075, -2.9680, -2.6818],
         [-2.4511, -2.6014, -2.2382, -2.5117],
         [-2.1281, -2.7477, -2.2391, -2.1176]]])
tensor2 is tensor([[[0.2676, 0.9966, 0.5811, 0.3843],
         [0.0281, 0.7074, 0.1975, 0.1958],
         [0.5649, 0.2287, 0.5049, 0.5535]],

        [[0.9755, 0.9108, 0.4719, 0.9500],
         [0.1631, 0.5108, 0.6517, 0.3014],
         [0.6009, 0.1044, 0.6107, 0.7513]]])
Subtraction between tensor1 and tensor2 is: tensor([[[ 0.0261, -0.8650,  0.0737,  0.3629],
         [ 0.8729, -0.5361,  0.7243

### Tensor Multiplication rules
![alt text](https://jillwilliams.github.io/Multiplying-Matrices/images/img11.png)
However, note that matrix multiplication rules is followed only for two dimensions of the two tensors being multiplied, the **third** dimension must be the same for both!

In [4]:
# tensor multiplication follows the standard matrix multiplication rules
# notice carefully the dimensions of tensor1 and tensor2 and the result
# also note that the first dimension in both tensors are same, tensors must also be of the same size
tensor1 = torch.rand(2,3,4) 
print(f"tensor1 is: {tensor1}")
tensor2 = torch.rand(3,4,3) 
print(f"tensor2 is {tensor2}")
# even torch.mm(t1, t2) works -> short for torch.matmul()
print(f"matrix multiplication of tensor1 and tensor2 is {torch.matmul(tensor1,tensor2)}")


torch.Size([2, 3, 4])
tensor1 is: tensor([[[0.7364, 0.0082, 0.9002, 0.3251],
         [0.2964, 0.5255, 0.8038, 0.3441],
         [0.2133, 0.3947, 0.7764, 0.5862]],

        [[0.6698, 0.0332, 0.3255, 0.1313],
         [0.0241, 0.0913, 0.0993, 0.0362],
         [0.5472, 0.0470, 0.5730, 0.3705]]])
tensor2 is tensor([[[0.6220, 0.0306, 0.3837],
         [0.7372, 0.0104, 0.2958],
         [0.1611, 0.0954, 0.9617],
         [0.4439, 0.2295, 0.4875]],

        [[0.4716, 0.1344, 0.7218],
         [0.2895, 0.3803, 0.8245],
         [0.0865, 0.0788, 0.6868],
         [0.9416, 0.5481, 0.6667]],

        [[0.9138, 0.8403, 0.6745],
         [0.7715, 0.7924, 0.1728],
         [0.3390, 0.0304, 0.7020],
         [0.5997, 0.5452, 0.7392]]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [18]:
# transposing tensors (to sometimes fix shape errors when doing matmul)
tensor1 = torch.rand(1,3,4)
print(tensor1)
print(tensor1.shape)
tensor1_t = tensor1.T 
print(tensor1_t)
print(tensor1.T.shape)

tensor([[[0.9625, 0.9139, 0.1755, 0.9461],
         [0.5411, 0.7292, 0.7929, 0.2978],
         [0.9263, 0.4485, 0.0297, 0.3003]]])
torch.Size([1, 3, 4])
tensor([[[0.9625],
         [0.5411],
         [0.9263]],

        [[0.9139],
         [0.7292],
         [0.4485]],

        [[0.1755],
         [0.7929],
         [0.0297]],

        [[0.9461],
         [0.2978],
         [0.3003]]])
torch.Size([4, 3, 1])
