In [2]:
import torch

### Tensor Reshaping explained

When you create a tensor with `x = torch.arange(1,11)`, you get a 1D tensor with shape `torch.Size([10])`. Visualizing this is as 10 boxes in a single row:

```
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

Now we'll shape it using `x.reshape(1,10)` where `(1,10)` is the new shape of the tensor.

When you reshape it to `x.reshape(1,10)` resulting in `torch.Size([1,10])`, the tensor still contains exactly 10 elements but you're reorganizing how these elements are conceptually arranged in a different dimensional structure.

The new shape represents a 2D tensor with **1 row and 10 columns**:

```
[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
```

Notice the extra set of brackets - this represents the added dimension. You now have a tensor with 2 dimensions (a matrix), but the first dimension has size 1. This is often called "adding a batch dimension" in deep learning contexts.

In PyTorch, reshaping operations like `view()` or `reshape()` never change the total number of elements in the tensor. They just reorganize how these elements are arranged within the dimensional structure.

> NOTE: you can also reshape a tensor using the syntax `torch.reshape(tensor, (dim1,dim2,...)`)

In [ ]:
x = torch.arange(1,11) 
print(x)
print(x.size())

# reshaping x
x_reshaped = x.reshape(1,10)
print(x_reshaped)
print(x_reshaped.size())

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
torch.Size([10])
torch.Size([1, 10])


### Changing the View of the Tensor

When you create a tensor out of a initial tensor by changing the view. it'll refer to the same tensor as the initial tensor (unlike in reshaping, where the new tensor after reshaping is a independent tensor in memory).


In [ ]:
x = torch.arange(1,6)
z = x.view(1,5)
print(x)
print(z)

# Here, changing z will change x (because they refer to the same tensor in memory!)
z[0,0]=100 # changing the element in 0th row and 0th col
print(x)


tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5]])
tensor([100,   2,   3,   4,   5])


In [ ]:
# We can also stack vectors along a dimension
y = torch.stack((x,x,x), dim=0)
y

tensor([[100,   2,   3,   4,   5],
        [100,   2,   3,   4,   5],
        [100,   2,   3,   4,   5]])

### Squeezing and Unsqueezing a Tensor

Squeezing: All the dimensions of size 1 will be removed from the tensor. The new tensor returned will share the same memory as the input tensor. So changing the new tensor, changes the input tensor

Unsqueezing: Returns a tensor with a dimension of size 1 inserted at a specified position. In this also, the returned tensor shares the same memory as the input tensor

In [4]:
x = torch.zeros(1,2,3,1)
print(x.size()) 

x_squeezed = torch.squeeze(x)
print(x_squeezed.size())

torch.Size([1, 2, 3, 1])
torch.Size([2, 3])


In [ ]:
x = torch.zeros(4,5) 
print(x.size())
x_unsqueezed = torch.unsqueeze(x, 0) # inserted a dimension of size 1 at the 0th dimension 
print(x_unsqueezed.size())

torch.Size([4, 5])
torch.Size([1, 4, 5])


### Permuting a Tensor

Changes the **order of dimensions** of a tensor. Again, the new tensor returned shares the same memory space as the original tensor

In [ ]:
x = torch.zeros(2,3,4) 
print(x.size()) 
x_permuted = torch.permute(x,(2,1,0)) 
# dimension of size 2 at 0th index (in input/original tensor) goes to 2nd index
# dimension of size 3 at 1st index goes to 1st index
# dimension of size 4 at 2nd index goes to 0th index
print(x_permuted.size())

torch.Size([2, 3, 4])
torch.Size([4, 3, 2])
