In [ ]:
import torch 

In [ ]:

x = torch.arange(1,10).reshape(1,3,3)
print(x); # is a 3D tensor


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
# print the 0th element of the 0th dimension (dim=0) (outermost bracket)
print(x[0]) # is a 2D tensor of shape (3,3)

# print the 0th element of the 1st dimension (dim=1)
print(x[0][0]) # is a 1D tensor of shape(3)

# print the 0th element of the 2nd dimension (dim=2) 
print(x[0][0][0]) # is a scaler of shape(0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [16]:
# you can also access all elements in a particular dimension using ":"

# print all elements inside the 0th dimension "1"
print(x[:])

# print all elements of the 0th dimension but 0th index ele of 1st dimension and 1st index ele of 2nd 
# dimension
print(x[:][0][1]) 

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([4, 5, 6])
